- name: Install Package Dependencies for
  apt:
    name:
    - apt-transport-https
    - ca-certificates 
    - curl
    state: present
- name: Get KeyRing for Kubernetes Archive
  shell: sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
- name: add Kubernetes Repository
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
- name: update packet sources
  apt: 
    name: 
    - kubeadm={{ kubernetes_version }}
    - kubelet={{ kubernetes_version }} 
    - kubectl={{ kubernetes_version }}
    state: present
    update_cache: yes
- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster
- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_ip }}:6443
  register: join_cluster
  # See: https://github.com/jetstack/cert-manager/issues/2640 with using kubeadm + calico + cert-manager
  environment:
    no_proxy: "$no_proxy,.svc,.svc.cluster.local"
- name: print out message
  debug:
    msg: "{{join_cluster}}"
