- hosts: microk8s-master
  tasks:
    - name: label Nodes for scheduling
      become: yes
      shell: |
        kubectl label nodes microk8s-master node=cloud
        kubectl label nodes microk8s-worker-0 node=edge1
        kubectl label nodes microk8s-worker-1 node=edge2
    - name: Git checkout
      become: true
      ansible.builtin.git:
        repo: 'https://github.com/eco-bench/eco-bench.git'
        dest: /etc/eco-bench
    - name: apply all pods
      become: yes
      shell: microk8s kubectl apply -f . --recursive
      args:
        chdir: /etc/eco-bench/dummy/kubernetes
    - name: Wait for default pods become ready
      become: yes
      shell: "microk8s kubectl wait --namespace=default --for=condition=Ready pods --timeout=600s --all"
      register: control_plane_pods_ready
      until: control_plane_pods_ready.rc == 0
      retries: 6
      delay: 10
      ignore_errors: true
    - name: get all pods
      become: yes
      shell: microk8s kubectl get pods -o wide
      register: output
    - name: Print output
      debug:
        msg: "pods: {{ output }}"