apiVersion: v1
kind: Service
metadata:
  name: sensor-device-service
spec:
  selector:
    app: sensor-device
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-device-deployment
  labels:
    app: sensor-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-device
  template:
    metadata:
      labels:
        app: sensor-device
    spec:
      containers:
        - name: sensor-device
          image: ecobench/sensor-edge-device:latest
          ports:
            - containerPort: 8080
          envFrom:
          # The ConfigMap we want to use
          - configMapRef:
              name: sensor-device-config
      imagePullSecrets:
        - name: github-regsecr
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-device-config
data:
  DEVICE_TYPE: "sensor"
  WORKER_PORT: "80"
  WORKER_IP: "http://sensor-ew1-service"
  WORKER_ENDPOINT: "sensorData"
  PING_INTERVAL: "200" #in ms
