- hosts: openyurt:!edge
  become: yes
  tasks:
    - name: Check Time
      command: date
      register: time
    - name: Print Version
      debug:
        msg: "date: {{ time.stdout }}"

# - hosts: openyurt:!edge
#   become: yes
#   tasks:
#     - name: install docker
#       shell: curl https://releases.rancher.com/install-docker/18.09.sh | sh

- hosts: openyurt:!edge
  become: yes
  roles:
    - geerlingguy.docker
    - master
  tasks:
    - name: Check Docker Version
      command: docker -v
      register: dockerVersion
    - name: Print Version
      debug:
        msg: "Docker Version: {{ dockerVersion.stdout }}"
    - name: Check Kubernetes Version
      command: kubectl version --short
      become: no
      register: kubernetesVersion
    - name: Print Version
      debug:
        msg: "Kubernetes Version: {{ kubernetesVersion.stdout }}"

- hosts: openyurt:!cloud
  become: yes
  roles:
    - geerlingguy.docker
    - worker
  tasks:
    - name: Check Docker Version
      command: docker -v
      register: dockerVersion
    - name: Print Version
      debug:
        msg: "Docker Version: {{ dockerVersion.stdout }}"

- hosts: openyurt:!edge
  become: yes
  roles:
    - cni

- hosts: openyurt:!edge
  become: yes
  roles:
    - openyurt

- hosts: openyurt:!edge
  become: yes
  tasks:
    - name: Check Docker Version
      command: date
      register: time
    - name: Print Version
      debug:
        msg: "date: {{ time.stdout }}"